import { z } from "zod";

import { isoDateSchema, isoTimestampSchema, schoolYearSchema } from "./enrollment-profile";

const nullableSchoolYearSchema = schoolYearSchema.nullable();
const nullableDateSchema = isoDateSchema.nullable();

export const reportTypeSchema = z.enum([
  "student_masterlist",
  "attendance_register_summary",
  "accomplishment_summary",
]);

export const reportFormatSchema = z.enum(["pdf", "xlsx"]);

export const reportDefinitionSchema = z
  .object({
    type: reportTypeSchema,
    format: reportFormatSchema,
    schoolYear: nullableSchoolYearSchema.optional(),
    dateFrom: nullableDateSchema.optional(),
    dateTo: nullableDateSchema.optional(),
  })
  .superRefine((definition, ctx) => {
    if (definition.type === "student_masterlist") {
      if (!definition.schoolYear) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ["schoolYear"],
          message: "School year is required for the student masterlist report",
        });
      }

      return;
    }

    if (!definition.dateFrom || !definition.dateTo) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["dateFrom"],
        message: "Date range is required for attendance and accomplishment reports",
      });
      return;
    }

    if (definition.dateFrom > definition.dateTo) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["dateFrom"],
        message: "Date range must start on or before the ending date",
      });
    }
  });

const exportAuditBaseSchema = z.object({
  id: z.string().trim().min(1, "Export audit ID is required"),
  reportType: reportTypeSchema,
  reportFormat: reportFormatSchema,
  generatedByUserId: z.string().trim().min(1, "Generated by user ID is required"),
  generatedAt: isoTimestampSchema,
  schoolYear: nullableSchoolYearSchema,
  dateFrom: nullableDateSchema,
  dateTo: nullableDateSchema,
  includedUnsyncedChanges: z.boolean(),
});

export const exportAuditRecordSchema = exportAuditBaseSchema.superRefine((record, ctx) => {
  if (record.reportType === "student_masterlist" && !record.schoolYear) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      path: ["schoolYear"],
      message: "School year is required for student masterlist exports",
    });
  }

  if (record.reportType !== "student_masterlist") {
    if (!record.dateFrom || !record.dateTo) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["dateFrom"],
        message: "Date range is required for attendance and accomplishment exports",
      });
      return;
    }

    if (record.dateFrom > record.dateTo) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["dateFrom"],
        message: "Date range must start on or before the ending date",
      });
    }
  }
});

export type ReportType = z.infer<typeof reportTypeSchema>;
export type ReportFormat = z.infer<typeof reportFormatSchema>;
export type ReportDefinition = z.infer<typeof reportDefinitionSchema>;
export type ExportAuditRecord = z.infer<typeof exportAuditRecordSchema>;
