/**
 * src/pwa/service-worker.ts
 *
 * Vite PWA injectManifest service worker.
 *
 * Strategy:
 *  - Cache only the installable shell (static assets injected by VitePWA).
 *  - ALL /api/ requests are NEVER cached — they always go to the network.
 *  - Personal-data and report responses are excluded from caching.
 *
 * This file is bundled separately by VitePWA's injectManifest strategy.
 * The self.__WB_MANIFEST placeholder is replaced at build time with the
 * precache manifest produced by workbox.
 */

/// <reference lib="webworker" />
import { clientsClaim } from "workbox-core";
import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching";
import { registerRoute, NavigationRoute } from "workbox-routing";
import { NetworkOnly } from "workbox-strategies";

declare const self: ServiceWorkerGlobalScope;

// Claim clients immediately so the SW activates without a page reload.
self.skipWaiting();
clientsClaim();

// Precache the app shell (static assets generated by VitePWA).
// __WB_MANIFEST is replaced at build time.
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// ---------------------------------------------------------------------------
// Bypass caching for ALL API requests (personal data policy)
// ---------------------------------------------------------------------------

registerRoute(({ url }) => url.pathname.startsWith("/api/"), new NetworkOnly());

// ---------------------------------------------------------------------------
// Navigation fallback — serve the shell for SPA client-side routing
// (Applies only to non-API navigation requests)
// ---------------------------------------------------------------------------

const navigationRoute = new NavigationRoute(
  async () => {
    const cache = await caches.open("dccms-shell-v1");
    const response = await cache.match("/");
    return response ?? Response.error();
  },
  {
    // Exclude /api/ paths from navigation fallback
    denylist: [/^\/api\//],
  },
);

registerRoute(navigationRoute);
