/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminStaffUsersRouteImport } from './routes/api/admin/staff-users'
import { Route as ApiAdminAuditEventsRouteImport } from './routes/api/admin/audit-events'
import { Route as ApiStaffDeviceDeactivateRouteImport } from './routes/api/staff/device/deactivate'
import { Route as ApiStaffDeviceActivateRouteImport } from './routes/api/staff/device/activate'
import { Route as ApiAdminStaffUsersUserIdDeactivateRouteImport } from './routes/api/admin/staff-users/$userId/deactivate'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStaffUsersRoute = ApiAdminStaffUsersRouteImport.update({
  id: '/api/admin/staff-users',
  path: '/api/admin/staff-users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuditEventsRoute = ApiAdminAuditEventsRouteImport.update({
  id: '/api/admin/audit-events',
  path: '/api/admin/audit-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffDeviceDeactivateRoute =
  ApiStaffDeviceDeactivateRouteImport.update({
    id: '/api/staff/device/deactivate',
    path: '/api/staff/device/deactivate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStaffDeviceActivateRoute = ApiStaffDeviceActivateRouteImport.update({
  id: '/api/staff/device/activate',
  path: '/api/staff/device/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStaffUsersUserIdDeactivateRoute =
  ApiAdminStaffUsersUserIdDeactivateRouteImport.update({
    id: '/$userId/deactivate',
    path: '/$userId/deactivate',
    getParentRoute: () => ApiAdminStaffUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/announcements': typeof AnnouncementsRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/staff': typeof StaffRouteWithChildren
  '/staff/': typeof StaffIndexRoute
  '/api/admin/audit-events': typeof ApiAdminAuditEventsRoute
  '/api/admin/staff-users': typeof ApiAdminStaffUsersRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/staff/device/activate': typeof ApiStaffDeviceActivateRoute
  '/api/staff/device/deactivate': typeof ApiStaffDeviceDeactivateRoute
  '/api/admin/staff-users/$userId/deactivate': typeof ApiAdminStaffUsersUserIdDeactivateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/announcements': typeof AnnouncementsRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/staff': typeof StaffIndexRoute
  '/api/admin/audit-events': typeof ApiAdminAuditEventsRoute
  '/api/admin/staff-users': typeof ApiAdminStaffUsersRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/staff/device/activate': typeof ApiStaffDeviceActivateRoute
  '/api/staff/device/deactivate': typeof ApiStaffDeviceDeactivateRoute
  '/api/admin/staff-users/$userId/deactivate': typeof ApiAdminStaffUsersUserIdDeactivateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/announcements': typeof AnnouncementsRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/staff': typeof StaffRouteWithChildren
  '/staff/': typeof StaffIndexRoute
  '/api/admin/audit-events': typeof ApiAdminAuditEventsRoute
  '/api/admin/staff-users': typeof ApiAdminStaffUsersRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/staff/device/activate': typeof ApiStaffDeviceActivateRoute
  '/api/staff/device/deactivate': typeof ApiStaffDeviceDeactivateRoute
  '/api/admin/staff-users/$userId/deactivate': typeof ApiAdminStaffUsersUserIdDeactivateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/announcements'
    | '/contact'
    | '/login'
    | '/staff'
    | '/staff/'
    | '/api/admin/audit-events'
    | '/api/admin/staff-users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/staff/device/activate'
    | '/api/staff/device/deactivate'
    | '/api/admin/staff-users/$userId/deactivate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/announcements'
    | '/contact'
    | '/login'
    | '/staff'
    | '/api/admin/audit-events'
    | '/api/admin/staff-users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/staff/device/activate'
    | '/api/staff/device/deactivate'
    | '/api/admin/staff-users/$userId/deactivate'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/announcements'
    | '/contact'
    | '/login'
    | '/staff'
    | '/staff/'
    | '/api/admin/audit-events'
    | '/api/admin/staff-users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/staff/device/activate'
    | '/api/staff/device/deactivate'
    | '/api/admin/staff-users/$userId/deactivate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  StaffRoute: typeof StaffRouteWithChildren
  ApiAdminAuditEventsRoute: typeof ApiAdminAuditEventsRoute
  ApiAdminStaffUsersRoute: typeof ApiAdminStaffUsersRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiStaffDeviceActivateRoute: typeof ApiStaffDeviceActivateRoute
  ApiStaffDeviceDeactivateRoute: typeof ApiStaffDeviceDeactivateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/staff-users': {
      id: '/api/admin/staff-users'
      path: '/api/admin/staff-users'
      fullPath: '/api/admin/staff-users'
      preLoaderRoute: typeof ApiAdminStaffUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/audit-events': {
      id: '/api/admin/audit-events'
      path: '/api/admin/audit-events'
      fullPath: '/api/admin/audit-events'
      preLoaderRoute: typeof ApiAdminAuditEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/device/deactivate': {
      id: '/api/staff/device/deactivate'
      path: '/api/staff/device/deactivate'
      fullPath: '/api/staff/device/deactivate'
      preLoaderRoute: typeof ApiStaffDeviceDeactivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/device/activate': {
      id: '/api/staff/device/activate'
      path: '/api/staff/device/activate'
      fullPath: '/api/staff/device/activate'
      preLoaderRoute: typeof ApiStaffDeviceActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/staff-users/$userId/deactivate': {
      id: '/api/admin/staff-users/$userId/deactivate'
      path: '/$userId/deactivate'
      fullPath: '/api/admin/staff-users/$userId/deactivate'
      preLoaderRoute: typeof ApiAdminStaffUsersUserIdDeactivateRouteImport
      parentRoute: typeof ApiAdminStaffUsersRoute
    }
  }
}

interface StaffRouteChildren {
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface ApiAdminStaffUsersRouteChildren {
  ApiAdminStaffUsersUserIdDeactivateRoute: typeof ApiAdminStaffUsersUserIdDeactivateRoute
}

const ApiAdminStaffUsersRouteChildren: ApiAdminStaffUsersRouteChildren = {
  ApiAdminStaffUsersUserIdDeactivateRoute:
    ApiAdminStaffUsersUserIdDeactivateRoute,
}

const ApiAdminStaffUsersRouteWithChildren =
  ApiAdminStaffUsersRoute._addFileChildren(ApiAdminStaffUsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  StaffRoute: StaffRouteWithChildren,
  ApiAdminAuditEventsRoute: ApiAdminAuditEventsRoute,
  ApiAdminStaffUsersRoute: ApiAdminStaffUsersRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiStaffDeviceActivateRoute: ApiStaffDeviceActivateRoute,
  ApiStaffDeviceDeactivateRoute: ApiStaffDeviceDeactivateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
